export { default as HomePage } from './HomePage'
export { default as PlayPage } from './PlayPage'
export { default as LeaderboardPage } from './LeaderboardPage'
export { default as UploadPage } from './UploadPage'
export { default as PrivacyPage } from './PrivacyPage'
